{"name": "Тест логина с несуществующими данными", "status": "passed", "steps": [{"name": "Проверяем, что приходит код 404 и нужное сообщение", "status": "passed", "start": 1740148813679, "stop": 1740148813680}], "attachments": [{"name": "stdout", "source": "a493828b-47fc-43e0-a92d-7fcb9578dade-attachment.txt", "type": "text/plain"}], "start": 1740148813307, "stop": 1740148813681, "uuid": "e69c409d-2a77-494a-a74f-cddf84ee1adc", "historyId": "74fc1065dd3cb0b08da6cbbbc7bb3faa", "testCaseId": "74fc1065dd3cb0b08da6cbbbc7bb3faa", "fullName": "tests.test_non_existent_data_login#test_non_existent_data_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_non_existent_data_login"}, {"name": "host", "value": "elizavetas-mbp"}, {"name": "thread", "value": "40111-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_non_existent_data_login"}]}